version: '3.3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/go/DockerFile
    ports:
      - '5000:5000'
    volumes:
      - ./src:/src
    tty: true
    depends_on:
      - db_golang

  # worker:
  #   container_name: worker
  #   build:
  #     context: .
  #     dockerfile: ./docker/worker/DockerFile
  #   volumes:
  #     - ./src:/src
  #   depends_on:
  #     - db_golang
  #     - backend

  # supervisor-go:
  #   container_name: supervisor-go
  #   build:
  #     context: .
  #     dockerfile: ./docker/supervisor/DockerFile
  #   tty: true
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./src:/src
  #     - ./log:/var/log
  #   depends_on:
  #     - db_golang
  #     - backend

  db_golang:
    container_name: db_golang
    image: postgres:14.1-alpine
    #    restart: always
    ports:
      - '5433:5432'
    volumes:
      - pgdata_go:/var/lib/postgresql/data
      - ./docker/backup/db:/tmp/db
    env_file:
      - .env

volumes:
  pgdata_go:
    name: pgdata_go
