version: '3.3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/go/DockerFile
    ports:
      - '8081:8081'
    volumes:
      - ./src:/src
    tty: true
    depends_on:
      - db_golang

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./docker/worker/DockerFile
    volumes:
      - ./src:/src
    depends_on:
      - db_golang
      - backend

  supervisor-go:
    container_name: supervisor-go
    build:
      context: .
      dockerfile: ./docker/supervisor/DockerFile
    tty: true
    env_file:
      - .env
    ports:
      - '8081:8081'
    volumes:
      - ./src:/src
      - ./log:/var/log
    depends_on:
      - db_golang
      - backend

  db_golang:
    container_name: db_golang
    image: postgres:14.1-alpine
    #    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
    name: pgdata
