FROM golang:1.22.0-alpine
LABEL authors="Ckala"
WORKDIR /src

ENV CGO_ENABLED=0

RUN apk update
RUN apk add gcompat mc curl

RUN cd /src go mod tidy


CMD ["dos2unix", "bootstrap_app.sh"]
ENTRYPOINT ["sh", "bootstrap_app.sh"]
# CMD ["./cmd/app"]
