env: "dev" # local, dev, prod
config_file: "local.yml"
http_server:
    address: "localhost:8082"
    timeout: 4s # время соединения, за какое сервер должен вернуть результат
    idle_timeout: 60s # время жизни соединения, на случай если клиент снова обратиться к серверу
database:
    postgres_host: "localhost"
    postgres_port: "5432"
    postgres_user: "pguser"
    postgres_password: "000000"
    postgres_db: "mydb"
