FROM golang:1.22.0-alpine as builder
LABEL authors="Ckala"
WORKDIR /src

ADD src/ /src/

ENV CGO_ENABLED=0

RUN apk update
RUN apk add gcompat curl

RUN cd /src go mod tidy


CMD ["dos2unix", "bootstrap_worker.sh"]

RUN go build -o worker ./worker/worker.go
RUN chmod 777 ./worker/worker

FROM alpine:3.14

WORKDIR /src

COPY --from=builder /src /src
CMD ["./worker/worker"]
