name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]

jobs:
#  check:
#    name: Check changed files
#    outputs:
#      api_service: ${{ steps.check_files.outputs.go-architecture-v2 }}
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 2
#
#      - name: check modified files
#        id: check_files
#        run: |
#          echo "=============== list modified files ==============="
#          git diff --name-only HEAD^ HEAD
#
#          echo "========== check paths of modified files =========="
#          git diff --name-only HEAD^ HEAD > files.txt
#          while IFS= read -r file; do
#            echo $file
#            if [[ $file == go-architecture-v2/* ]]; then
#              echo "::set-output name=go-architecture-v2::true"
#            else
#              echo "file does not belong to any service"
#            fi
#          done < files.txt

  go-architecture-v2:
#    needs: check
#    if: needs.check.outputs.go-architecture-v2 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        uses: docker/build-push-action@v4
        with:
#          context: api_go_template_service/
          file: ./docker/go/DockerFile
          push: true
          tags: ckala62rus/go-template-service:latest
